### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by ckclark** [przemoc/metastore#31]
When I install metastore on Cygwin. It will show the following error.

```console
gcc  -g -Wall -pedantic -std=c99 -D_FILE_OFFSET_BITS=64 -O2  -o metaentry.o -c ./src/metaentry.c
./src/metaentry.c:35:24: fatal error: bsd/string.h: No such file or directory
 #include <bsd/string.h>
                        ^
compilation terminated.
Makefile:56: recipe for target 'metaentry.o' failed
make: *** [metaentry.o] Error 1
```

I think there could be more generic way to use string.h but not bsd/string.h?

**Comment by przemoc** [comment]
Metastore in this repository requires [libbsd](http://libbsd.freedesktop.org/) (since 7c7eabd), which is at least easily available in most Linux distributions. I'm sorry, I don't use cygwin, but maybe it's in some cygwin repositories too?

In the worst case you can always go with 7c7eabd^, i.e. dbf59f5. You won't get dump action, but otherwise it should be ok, because commits after 7c7eabd were only cleanings-oriented.

**Comment by ckclark** [comment]
I found libbsd on [cygwinports] (http://cygwinports.org/) and followed the steps to install libbsd library. Now it works. Thanks.
